name: webbinder
channels:
  - conda-forge
dependencies:
  - python=3.9
  - aiohttp
  - aiofiles
  - beautifulsoup4
  - weasyprint
  - markdownify
  - tqdm
  - xhtml2pdf
  - markdown
  - validators
  - pytest
  - pytest-asyncio